name: '이슈 생성'
description: '이슈를 생성하며, 생성된 이슈는 Jira와 연동됩니다.'
labels: [order]
title: '이슈 이름을 작성해주세요.'
body:
  - type: input
    id: parentKey
    attributes:
      label: 'Epic/Story Ticket Number'
      description: 'Ticket Number를 기입해주세요.'
      placeholder: 'SB-00'
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: '이슈 내용'
      description: '이슈에 대해 간략하게 설명해주세요.'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '체크리스트(Tasks)'
      description: '해당 이슈에 대해 필요한 작업목록을 작성해주세요'
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true
